spring:
    application:
        name=sensorreader
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:localhost;DB_CLOSE_ON_EXIT=FALSE
        username: admin
        password:
temperature: 192.168.100.250, 192.168.100.251